version: '3'
services:
  dragons_app:
    build: .
    env_file: .env
    container_name: dragons_app
    ports:
      - 8080:8080
    depends_on:
      - dragons_db
  dragons_db:
    image: mysql/mysql-server
    container_name: dragons_db
    environment:
      - MYSQL_USER=dragons
      - MYSQL_PASSWORD=dragons
      - MYSQL_DATABASE=dragons_db
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
